sudo: required

services:
  - docker

before_install:
  - docker build -t 1fckdup/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 1fckdup/react-test npm test

after_success:
  # Build images
  - docker build -t 1fckdup/multi-client ./client
  - docker build -t 1fckdup/multi-nginx ./nginx
  - docker build -t 1fckdup/multi-server ./server
  - docker build -t 1fckdup/multi-worker ./worker
  
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Push them to Docker Hub
  - docker push 1fckdup/multi-client
  - docker push 1fckdup/multi-nginx
  - docker push 1fckdup/multi-server
  - docker push 1fckdup/multi-worker
